const tableData = [
  {
    srno: 1,
    Date: 'string',
    Time: 'string',
    OrderId: 'string',
    TradeId: 'string',
    Quality: 'string',
    BuyerName: 'string',
    BuyerLocation: 'string',
    BuyerQuantity: 'string',
    BuyerRate: 10,
    PaymentTerms: 'string',
    SellerName: 'string',
    SellerLocation: 'string',
    SellerQuantity: 'string',
    DeliveryTerms: 'string',
    DeliveryDue: 'string',
    MaterialImage: 'string',
    Status: 'string',
    TradeValidity: 'string',
    SellerResponse: 0,
    PaymentDate: 'string',
    RejectedMessage: 'string',
    DispatchDate: 'string',
    Quantity: 10,
    InvoiceAmount: 10,
    InvoiceImage: 'string',
    WeightSlip: 'string',
    VehicleNumber: 'string',
    TransporterContact: 'string',
    DeliveryDate: 'string',
    DeliveryWeightSlip: 'string',
    PaymentDueDate: 'string',
    UtrNo: 'string',
    PaymentScreenshot: 'string',
    Commision: 'string',
    Name: 'string',
    Address: 'string',
    Location: 'strin',
    AverageMonthQuantity: 100,
    Salutation: 'string',
    FirstName: 'string',
    LastName: 'string',
    Designation: 'string',
    PhoneNo: '100',
    AlternateNo: '100',
    Email: 'string',
    Password: 'string',
    GSTNo: 'string',
    PANNo: 'string',
    BankName: 'string',
    AccountName: 'string',
    AccountNo: '100',
    AccountType: 'string',
    IFSCCode: 'string',
    BankBranch: 'string',
    CancelCheque: 'string',
    CustomerName: 'string',
    Role: 'string',
    StartDate: 'string',
    EndDate: 'string',
    Remaining: 'string',
    Subscription: 'string',
    IsActive: 1,
    Uid:1,
    IsSubscribe:1
  }

];
const paymentData = [
  {
    srno: 10,
    TradeDate: '',
    TradeId: '10',
    BuyerName: 'string',
    SellerName: 'string',
    PaymentDueDate: 'string',
    InvoiceAmount: 10,

  }
]
const SubscriptionData = [{
  srno: 10,
  Name: 'string',
  Role: 'string',
  Location: 'string',
  StartDate: '',
  EndDate: '',
  Remaining: '',
  Status: 'string'
}]

export { tableData, paymentData };
